"""Tests for portal icon (AC6 — FR-20260426-portal-icon-design).

Verifies:
- portal.html has a <link rel="icon"> favicon tag
- src/data/portal_icon.png exists
- src/data/portal_icon.ico exists and contains multiple resolutions
- src/data/portal_icon_config.json has a non-empty prompt
- portal.html sigil span carries data-icon-prompt attribute
- portal.html has tooltip CSS for the sigil
- regen_portal_icon.py script exists and is importable
"""
import json
import re
import importlib.util
from pathlib import Path

import pytest

PIL = pytest.importorskip("PIL", reason="Pillow not installed — skipping PIL-dependent icon tests")
Image = PIL.Image

WORKSPACE_ROOT = Path(r"f:\⊕Workspace")
PORTAL_HTML    = WORKSPACE_ROOT / "reports" / "portal.html"
PORTAL_PNG     = WORKSPACE_ROOT / "src" / "data" / "portal_icon.png"
PORTAL_ICO     = WORKSPACE_ROOT / "src" / "data" / "portal_icon.ico"
ICON_CONFIG    = WORKSPACE_ROOT / "src" / "data" / "portal_icon_config.json"
REGEN_SCRIPT   = WORKSPACE_ROOT / "tools" / "regen_portal_icon.py"


def test_portal_icon_png_exists() -> None:
    assert PORTAL_PNG.is_file(), f"Missing: {PORTAL_PNG}"


def test_portal_icon_ico_exists() -> None:
    assert PORTAL_ICO.is_file(), f"Missing: {PORTAL_ICO}"


def test_portal_icon_ico_multi_resolution() -> None:
    """portal_icon.ico must contain at least the 16x16 and 32x32 sizes."""
    if not PORTAL_ICO.is_file():
        pytest.skip("portal_icon.ico not present — generated by DALL-E hook, not committed")
    img = Image.open(PORTAL_ICO)
    sizes = img.info.get("sizes") or set()
    if not sizes:
        assert img.format == "ICO", f"Expected ICO format, got {img.format}"
        return
    assert (16, 16) in sizes, f"16x16 frame missing from ICO. Found: {sizes}"
    assert (32, 32) in sizes, f"32x32 frame missing from ICO. Found: {sizes}"


def test_portal_html_has_favicon() -> None:
    assert PORTAL_HTML.is_file(), f"Missing: {PORTAL_HTML}"
    html = PORTAL_HTML.read_text(encoding="utf-8")
    assert 'rel="icon"' in html, '<link rel="icon"> not found in portal.html'


def test_portal_html_favicon_is_base64_ico() -> None:
    html = PORTAL_HTML.read_text(encoding="utf-8")
    assert 'data:image/x-icon;base64,' in html, (
        "Favicon is not an inline base64 ICO in portal.html"
    )


# ── Dynamic icon / config tests ────────────────────────────────────────────────

def test_icon_config_exists_with_prompt() -> None:
    """portal_icon_config.json must exist and contain a non-empty prompt."""
    assert ICON_CONFIG.is_file(), f"Missing: {ICON_CONFIG}"
    cfg = json.loads(ICON_CONFIG.read_text(encoding="utf-8"))
    assert cfg.get("prompt"), "portal_icon_config.json has an empty prompt field"


def test_icon_config_has_required_fields() -> None:
    """portal_icon_config.json must have model, size, quality, generated_at."""
    cfg = json.loads(ICON_CONFIG.read_text(encoding="utf-8"))
    for field in ("model", "size", "quality", "generated_at"):
        assert field in cfg, f"portal_icon_config.json missing field: {field}"


def test_portal_html_sigil_has_icon_prompt_attribute() -> None:
    """The ⊕ sigil span in portal.html must carry a data-icon-prompt attribute."""
    html = PORTAL_HTML.read_text(encoding="utf-8")
    assert 'data-icon-prompt=' in html, (
        "Sigil span in portal.html is missing data-icon-prompt attribute"
    )


def test_portal_html_has_sigil_tooltip_css() -> None:
    """portal.html must include CSS for the sigil hover tooltip."""
    html = PORTAL_HTML.read_text(encoding="utf-8")
    assert 'data-icon-prompt]:hover::after' in html, (
        "Tooltip CSS (.sigil[data-icon-prompt]:hover::after) not found in portal.html"
    )


def test_portal_html_sigil_prompt_matches_config() -> None:
    """portal.html must have a non-empty data-icon-prompt attribute on the sigil span.

    When --vary is used the injected prompt differs from the stored base prompt, so
    we only verify presence and non-emptiness rather than an exact string match.
    """
    html = PORTAL_HTML.read_text(encoding="utf-8")
    m = re.search(r'data-icon-prompt="([^"]+)"', html)
    assert m is not None, "data-icon-prompt attribute missing from portal.html"
    assert len(m.group(1)) > 20, "data-icon-prompt is present but suspiciously short"


def test_regen_script_exists() -> None:
    """tools/regen_portal_icon.py must exist."""
    assert REGEN_SCRIPT.is_file(), f"Missing: {REGEN_SCRIPT}"


def test_regen_script_importable() -> None:
    """tools/regen_portal_icon.py must be parseable as a Python module."""
    spec = importlib.util.spec_from_file_location("regen_portal_icon", REGEN_SCRIPT)
    assert spec is not None, "Could not create module spec for regen_portal_icon.py"
    module = importlib.util.module_from_spec(spec)
    # Loading (not executing) the module should not raise
    try:
        spec.loader.exec_module(module)  # type: ignore[union-attr]
    except SystemExit:
        pass  # argparse calls sys.exit on --help; that's fine


# ── ❤Music localhost server tests ─────────────────────────────────────────────

_MUSIC_SERVERS = {
    "Music Dashboard": 5050,
    "TJD Radio":       8100,
    "Guitar Trainer":  5055,
}

_ALL_SERVERS = {
    **_MUSIC_SERVERS,
    "FR server":              7474,
    "Executive Audio Brief":  8200,
}

_MUSIC_SCRIPTS = {
    5050: r"f:\❤Music\src\analysis\music_dashboard.py",
    8100: r"f:\❤Music\src\radio\tjd_radio.py",
    5055: r"f:\❤Music\src\training\musician_training_ui.py",
}

_ALL_SCRIPTS = {
    **_MUSIC_SCRIPTS,
    7474: r"f:\⊕Workspace\src\utils\fr_server.py",
    8200: r"f:\👁AI-Manifest\tools\executive_audio_brief.py",
}


def test_portal_html_has_music_server_iframes() -> None:
    """portal.html must embed iframes for all three ❤Music localhost servers."""
    html = PORTAL_HTML.read_text(encoding="utf-8")
    for name, port in _MUSIC_SERVERS.items():
        assert f"localhost:{port}" in html or f"127.0.0.1:{port}" in html, (
            f"portal.html missing iframe for {name} (port {port})"
        )


def test_portal_html_has_server_status_dots() -> None:
    """portal.html must have status indicator elements for each music server."""
    html = PORTAL_HTML.read_text(encoding="utf-8")
    for name, port in _MUSIC_SERVERS.items():
        assert f"dot-{port}" in html, (
            f"portal.html missing status dot element for {name} (dot-{port})"
        )


def test_music_server_scripts_exist() -> None:
    """The ❤Music server Python scripts that the launcher starts must exist on disk."""
    for port, script_path in _MUSIC_SCRIPTS.items():
        assert Path(script_path).is_file(), (
            f"Server script missing for port {port}: {script_path}"
        )


def test_all_server_scripts_exist() -> None:
    """All server scripts (❤Music + FR + AI brief) must exist on disk."""
    for port, script_path in _ALL_SCRIPTS.items():
        assert Path(script_path).is_file(), (
            f"Server script missing for port {port}: {script_path}"
        )


def test_portal_html_has_fr_and_brief_servers() -> None:
    """portal.html must embed fr_dashboard.html (uses :7474) and the AI brief iframe (:8200)."""
    html = PORTAL_HTML.read_text(encoding="utf-8")
    assert "fr_dashboard.html" in html, "portal.html missing fr_dashboard.html pane"
    assert "127.0.0.1:8200" in html or "localhost:8200" in html, (
        "portal.html missing Executive Audio Brief iframe (:8200)"
    )


def test_staged_launcher_starts_music_servers() -> None:
    """The staged open_portal.ps1 launcher must contain start commands for all servers.

    This is a structural check — we verify the launcher was written correctly
    without actually starting servers in the test environment.
    Skips gracefully if the staged file doesn't exist yet (first run before shortcut creation).
    """
    import os
    staged_ps1 = Path(os.environ.get("LOCALAPPDATA", "")) / "WorkspacePortal" / "open_portal.ps1"
    if not staged_ps1.is_file():
        import pytest
        pytest.skip("Staged launcher not yet created — run create_desktop_shortcut.py first")
    content = staged_ps1.read_text(encoding="utf-8-sig")
    for name, port in _ALL_SERVERS.items():
        assert str(port) in content, (
            f"Staged open_portal.ps1 missing start command for {name} (port {port})"
        )
    assert "Start-Process" in content, "Staged open_portal.ps1 missing Start-Process call"
